backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "/public/images/posts" # Location where files will be stored in the repo
public_folder: "/images/posts" # The src attribute for uploaded media

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Display label in the CMS
    folder: "src/content/blog" # Directory for storing documents
    create: true # Allow creating new blog posts
    slug: "{{slug}}" # Template for filenames
    fields: # Define the fields for each blog post
      - { label: "ID", name: "id", widget: "string", required: false } 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Date", name: "date", widget: "datetime", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Categories", name: "categories", widget: "list", default: ["others"], required: false }
      - { label: "Draft", name: "draft", widget: "boolean", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", required: false }

  - name: "homepage"
    label: "Homepage"
    editor:
      preview: false
    files:
      - name: "homepage"
        label: "Homepage Content"
        file: "src/content/homepage/index.md" # Path to homepage.md
        fields:
          - { label: "Banner Title", name: "banner.title", widget: "string" }
          - { label: "Banner Second Title", name: "banner.secondTitle", widget: "string" }
          - { label: "Banner Content", name: "banner.content", widget: "text" }
          - { label: "Banner Image", name: "banner.image", widget: "image" }
          - label: "Banner Button"
            name: "banner.button"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - { label: "Enable", name: "enable", widget: "boolean" }
          - label: "About Section"
            name: "about"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Second Title", name: "secondTitle", widget: "string" }
              - { label: "Side Text", name: "sideText", widget: "string" }
              - { label: "Description", name: "description", widget: "markdown" }
          - label: "Social Links"
            name: "social.links"
            widget: "list"
            fields:
              - { label: "Platform", name: "platform", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
          - label: "Key Features"
            name: "key_features"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Feature List"
                name: "feature_list"
                widget: "list"
                fields:
                  - { label: "Icon", name: "icon", widget: "string" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Content", name: "content", widget: "text" }
          - label: "Service"
            name: "service"
            widget: "object"
            fields:
              - label: "Homepage Tab"
                name: "homepage_tab"
                widget: "object"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }
                  - label: "Tab List"
                    name: "tab_list"
                    widget: "list"
                    fields:
                      - { label: "Title", name: "title", widget: "string" }
                      - { label: "Icon", name: "icon", widget: "string" }
                      - { label: "Image", name: "image", widget: "image" }
              - label: "Our Service"
                name: "our_service"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }
                  - { label: "Image", name: "image", widget: "image" }
                  - label: "List"
                    name: "list"
                    widget: "list"
                    field: { label: "Item", name: "item", widget: "string" }

          - label: "Testimonial"
            name: "testimonial"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Testimonial List"
                name: "testimonial_list"
                widget: "list"
                fields:
                  - { label: "Author", name: "author", widget: "string" }
                  - { label: "Avatar", name: "avatar", widget: "image" }
                  - { label: "Organization", name: "organization", widget: "string" }
                  - { label: "Rating", name: "rating", widget: "string" }
                  - { label: "Content", name: "content", widget: "text" }

